name: Make Cards List
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  makelist:
    name: Make List
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get JSON
        run: |
          $token = ((curl "https://mp.t-union.com/api//bonc/inPursuitOfTreasure") | ConvertFrom-Json).howdoudo
          curl -o "Cards.json" -H "Authorization: Bearer ${token}" "https://mp.t-union.com/api/selectCards?pageSize=999"

      - name: Push JSON
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "GitHub Actions Update"
          git push
