name: Make Cards List
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  makelist:
    name: Make List
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get Original JSON Hash
        run: |
          if (Test-Path Cards.json) {
              $Original_JSON_Hash = (Get-FileHash Cards.json).Hash
              Write-Output original_json_hash=$Original_JSON_Hash
              Write-Output original_json_hash=$Original_JSON_Hash >> ${{ github.env }}
          }

      - name: Get JSON
        run: |
          curl -o 'Cards.json' -H 'Authorization: Bearer ${{ secrets.WECHAT_ACESS_TOKEN }}' -H 'Content-Type: application/json' 'https://mp.t-union.com/api/selectCards?pageSize=999'

      - name: Push JSON
        if: ${{ hashFiles('Cards.json') != env.original_json_hash }}
        run: |
          git commit -m "GitHub Actions ${{ github.run.attempt }}"
          git push
